laundry/laundry/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'laundry.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^status/', include('status.urls', namespace="status")),
)

laundry/status/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('status.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<query_id>\d+)/$', 'detail', name='detail')
)

laundry/status/models.py
from django.db import models

class Query(models.Model):
    query_text = models.CharField(max_length=200)
    def __unicode__(self):
        return u'%s' % (self.query_text)

class Response(models.Model):
    query = models.ForeignKey(Query)
    machine_type = models.CharField(max_length=200)
    machine_in_use = models.IntegerField(default=-1)
    def __unicode__(self):
        return u'%s' % (self.machine_type)

laundry/status/views.py
from django.shortcuts import get_object_or_404, render
from status.models import Query, Response

def index(request):
    query_list = Query.objects.all()
    context = {'query_list': query_list}
    return render(request, 'index.html', context)

def detail(request, query_id):
    query = get_object_or_404(Query, pk=query_id)
    return render(request, 'detail.html', {'query': query})

laundry/status/templates/detail.html
<h1>{{ query.query_text }}</h1>
<ul>
  {% for response in query.response_set.all %}
    <li>{{ response.machine_type }}</li>
  {% endfor %}
</ul>

laundry/status/templates/index.html
{% if query_list %}
  <ul>
    {% for one_query in query_list %}
      <li><a href="{% url 'status:detail' one_query.id %}">{{ one_query.query_text }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No laundry services are available.</p>
{% endif %}